powertest <-read.table("household_power_consumption.txt",header=TRUE,sep = ";", stringsAsFactors=FALSE, na.strings="?")
powertest$Date <-as.Date(powertest$Date, format="%d/%m/%Y")
powertest$Global_active_power <-as.numeric(powertest$Global_active_power)
powersub <- powertest[(powertest$Date >= "2007-02-01") & (powertest$Date <= "2007-02-02"), ]
x <-strptime(paste(powersub$Date, powersub$Time), format = "%Y-%m-%d %H:%M:%S")
powersub[,4] <-as.numeric(powersub[,4])
powersub[,5] <-as.numeric(powersub[,5])
powersub[,7] <-as.numeric(powersub[,7])
powersub[,8] <-as.numeric(powersub[,8])
powersub[,9] <-as.numeric(powersub[,9])
png(file="Plot4.png")
par(mfrow=c(2,2))
powersub[,3] <-as.numeric(powersub[,3])
plot(x, powersub$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", pch="")
lines(x, powersub$Global_active_power)
plot(x, powersub[,5], pch="", ylab="Voltage", xlab="datetime")
lines(x, powersub[,5])
plot(x, powersub[,7], xlab="", ylab="Energy Sub Metering", pch="")
lines(x, powersub[,7], xlab="", ylab="Energy Sub Metering",)
lines(x, powersub[,8], xlab="", ylab="Energy Sub Metering", col="red")
lines(x, powersub[,9], xlab="", ylab="Energy Sub Metering", col="blue")
legend("topright", lty=c(1,1,1), col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(x, powersub[,4], xlab="datetime", ylab="Global_reactive_power", pch="")
lines(x, powersub[,4])
dev.off() 