powertest <-read.table("household_power_consumption.txt",header=TRUE,sep = ";", stringsAsFactors=FALSE, na.strings="?")
powertest$Date <-as.Date(powertest$Date, format="%d/%m/%Y")
powertest$Global_active_power <-as.numeric(powertest$Global_active_power)
powersub <- powertest[(powertest$Date >= "2007-02-01") & (powertest$Date <= "2007-02-02"), ]
x <-strptime(paste(powersub$Date, powersub$Time), format = "%Y-%m-%d %H:%M:%S")
powersub[,3] <-as.numeric(powersub[,3])
plot(x, powersub$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", pch="")
lines(x, powersub$Global_active_power)
dev.copy(png, file="Plot2.png")
dev.off() 