powertest <-read.table("household_power_consumption.txt",header=TRUE,sep = ";")
powertest$Date <-as.Date(powertest$Date, format="%d/%m/%Y")
powertest$Global_active_power <-as.numeric(powertest$Global_active_power)
powersub <- powertest[(powertest$Date >= "2007-02-01") & (powertest$Date <= "2007-02-02"), ]
powersub[,4] <-as.numeric(powersub[,4])
powersub[,5] <-as.numeric(powersub[,5])
powersub[,7] <-as.numeric(powersub[,7])
powersub[,8] <-as.numeric(powersub[,8])
powersub[,9] <-as.numeric(powersub[,9])
png(file="Plot4.png")
par(mfrow=c(2,2))
plot(powersub$Global_active_power, xlab="", ylab="Energy sub metering", xaxt="n", yaxt="n", pch="")
lines(powersub$Global_active_power, xlab="", ylab="Energy sub metering", xaxt="n", yaxt="n")
axis(1, at=c(0,1500,2900), labels=c("Thu","Fri","Sat"))
axis(2, at=c(0,1000,2000,3000), labels=c("0","2","4","6"))
plot(powersub[,5], pch="", ylab="Voltage", xlab="datetime", xaxt="n", yaxt="n")
lines(powersub[,5])
axis(1, at=c(0,1500,2900), labels=c("Thu","Fri","Sat"))
axis(2, at=c(800,1000,1200,1400,1600,1800,2000), labels=c("234","235","236","237","238","239","240"))
plot(powersub[,7], xlab="", ylab="Energy Sub Metering", xaxt="n", yaxt="n", pch="")
lines(powersub[,7], xlab="", ylab="Energy Sub Metering", xaxt="n", yaxt="n")
lines(powersub[,8], xlab="", ylab="Energy Sub Metering", xaxt="n", yaxt="n", col="red")
lines(powersub[,9], xlab="", ylab="Energy Sub Metering", xaxt="n", yaxt="n", col="blue")
axis(1, at=c(0,1500,2900), labels=c("Thu","Fri","Sat"))
axis(2, at=c(2,10,20,30), labels=c("0","10","20","30"))
legend("topright", lty=c(1,1,1), col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(powersub[,4], xlab="datetime", ylab="Global_reactive_power", xaxt="n", yaxt="n", pch="")
lines(powersub[,4])
axis(1, at=c(0,1500,2900), labels=c("Thu","Fri","Sat"))
axis(2, at=c(0,45,90,135,180,225), labels=c("0.0","0.1","0.2","0.3","0.4","0.5"))
dev.off()