powertest <-read.table("household_power_consumption.txt",header=TRUE,sep = ";")
powertest$Date <-as.Date(powertest$Date, format="%d/%m/%Y")
powertest$Global_active_power <-as.numeric(powertest$Global_active_power)
powersub <- powertest[(powertest$Date >= "2007-02-01") & (powertest$Date <= "2007-02-02"), ]
powersub[,7] <-as.numeric(powersub[,7])
powersub[,8] <-as.numeric(powersub[,8])
powersub[,9] <-as.numeric(powersub[,9])
plot(powersub$Global_active_power, xlab="", ylab="Energy sub metering", xaxt="n", yaxt="n", pch="")
lines(powersub$Global_active_power, xlab="", ylab="Energy sub metering", xaxt="n", yaxt="n")
axis(1, at=c(0,1500,2900), labels=c("Thu","Fri","Sat"))
axis(2, at=c(0,1000,2000,3000), labels=c("0","2","4","6"))
dev.copy(png, file="Plot2.png")
dev.off()